#!/bin/bash
# Wrapper for crash-digger to handle architecture-specific flags.

ARCH=$1

COMMAND=("/usr/bin/crash-digger" "-v" "-c" "/app/config-apport" "-C" "/home/ubuntu/cache-${ARCH}" "--crash-db=ubuntu-${ARCH}" "-d" "/srv/retracers/apport-duplicates/apport_duplicates.db" "--gdb-sandbox" "--auth" "/app/launchpad-credentials")

# Only publish the database on amd64
if [ "$ARCH" == "amd64" ]; then
    COMMAND+=("--publish-db" "/srv/retracers/apport-duplicates")
fi

# Execute the command
exec "${COMMAND[@]}"
